name: message_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase (updated to latest versions)
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  firebase_messaging: ^16.0.3
  firebase_crashlytics: ^5.0.3
  cloud_functions: ^6.0.3
  firebase_database: ^12.0.3
  flutter_local_notifications: ^19.5.0

  # State Management (Riverpod)
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  # Utilities
  equatable: ^2.0.7
  connectivity_plus: ^7.0.0
  dartz: ^0.10.1
  uuid: ^4.5.1
  rxdart: ^0.28.0

  # ML Kit for language detection
  google_mlkit_commons: ^0.11.0
  google_mlkit_language_id: ^0.13.0

  # Local Storage (drift)
  drift: ^2.29.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.5
  path: ^1.9.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  workmanager: ^0.9.0
  flutter_list_view: ^1.1.29

  riverpod: any
  mutex: ^3.1.0
dev_dependencies:
  flutter_lints: ^6.0.0

  # Code generation
  drift_dev: ^2.29.0
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  build_runner: ^2.7.1

flutter:
  uses-material-design: true
